version: '3.4'

services:
  crawlwebtygiabackend:
    image: crawlwebtygiabackend
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
